spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_recruitment?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: mzrfviwhninayh

